dist: bionic

language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "bloody-azimus"
    token: $SONAR_TOKEN

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - make clean
  - coveralls --root . -E ".*external.*" -E ".*tests.*" -E ".*main.c"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

notifications:
  email: false